---
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    template: ./resources/aog-latex-ms.tex
  word_document:
    reference_docx: ./resources/aog_word_style.docx
fontfamily: mathpazo
fontsize: 11pt
anonymous: false
endnotes: false
pagenumber: 1
bibliography: ../project.bib
biblio-style: ./resources/ajs.bst
title: "Does the Media Influence Voters: A Study of the 2012 and 2016 Elections"
author:    
- affiliation: University of Oregon, Sociology
  name: Mary Follo 
- affiliation: Some Research University
  name: My co-author
keywords: keywords
thanks: Thanks to people and stuff
abstract: This is a test abstract
---

# Introduction

The role of media in voting has always played a significant role in U.S. politics. From political propaganda pamphlets during the revolutionary war to the political machine era; parties, candidates and their campaigns have worked to exert influence over voters. Today, the media is one of the strongest resources candidates have at their disposal to mobilize their voters. All aspects of campaigns are broadcast on television, the Internet and social media in an attempt to influence behaviors. In fact, recent research, when studying the effect of Fox news bias, has shown that the media can have a sizable political impact (DellaVigna and Kaplan, 2006). In the 2008 election for example, Oprah Winfrey’s celebrity endorsement of Barack Obama on her television show can be correlated with an extra one million votes during the election. Hence, the “Oprah Effect” or ability for democracy to be strengthened among low-awareness voters through the consumption of soft news media was created (Baum, 2006). At the time of the 2008 election however, a new media type was just taking shape. Social media that is now heavily utilized for campaigns was just becoming accessible to users with Facebook and Twitter taking shape in 2006 and Instagram in 2008. These new forms of social media are just one more way that candidates and campaigns can exert influence over voters. 
Understanding the role of media in public opinion and behavior has historically been hotly debated among three distinct models: the hypodermic model, the minimum effects model and the constructivist model. The hypodermic model asserts that “the mass media exercised a powerful and persuasive influence” on a public that was “inherently susceptible to manipulation” (Curran, Gurevitch and Woollacott, 1982). Post-World War I, scholars theorized that the media was seen as a brainwashing agent that preyed on the unknowing public mind that could be completely consumed by media agency.  This pessimistic theory has proven empty over time and does not take into account individual agency but instead assumes each person is a blank slate, a tabula rasa that is waiting for the media or some other influence to give them opinions. In the 1950’s and 60’s a new school of thought emerged called the minimal effects theory. Introduced by Joseph Klapper, the minimal effects theory finds that “only a tiny fraction of voters actually changed their vote intentions during an election campaign, that audience motivations and prior beliefs influenced the interpretations of persuasive messages” (Neuman& Guggenheim, 2011). The idea of media manipulation shifted from “what the media does to people to what the people do with the media” (Gamson, 1988). In this way, the minimal effects approach tells a narrative about a voter with more agency but does not take into account the real role that media framing and priming play in political behavior. These two early theories of media influence portrayed the American citizen as an all of nothing individual, either completely consumed by the media or completely obstinate to it. 
Instead, I focus on the use of the constructivist model that “takes into account the changing nature of the media’s power as it interacts among voters who influence each other while contributing to the construction of messages, meanings and outcomes in the electoral process” (Gamson, 1988). The constructivist model allows one’s personal social discourse to align with the media discourse that one is influenced by to construct their own opinions and vote choice by melding information obtained from the media with their existing beliefs (Neuman et. al, 1992). In this way, citizens are able to consume a large variety of news media and construct their own political knowledge out of what they believe is most relevant. The agenda setting and priming that is absent in the minimal effects approach is welcomed in the constructivist approach and shows that the media can be both directly and indirectly persuasive through the frames it chooses to shape discourse with (Armoudian & Crigler, 2010). As technology continues to develop, more factors will be added to the complex interplay that constructs each individual’s political discourse. Political meaning and the construction of personal voting behavior then is not solely determined by media effect, nor does it have a minimal effect. Media, especially social media can be effective helping shape one’s thoughts through its news generating ability, however when it comes to actual decision making and voter behavior, individuals tend to rely on their interpersonal networks for direction. 
As mass media like social media have gained prominence in American society, citizens have become dependent upon them for a variety of news information. The reliance on social media especially by youths for news relates to Ball-Rokeach and DeFleur’s dependency theory. Dependency theory states that, “audiences are dependent on media information resources which leads to modifications in both personal and social processes” (Ball-Rokeach and DeFleur, 1976). What I believe to be an extension of the constructivist model, dependency theory not only states media’s role in helping create discourses but it gives power to mass media by acknowledging the increasing reliance upon it for information and resources. “In American society, the media are presumed to have several unique functions. They operate as a Fourth estate gathering and delivering information about the actions of the government; […] they constitute the principle source of the ordinary citizen’s conceptions of national and world events; they provide enormous amounts of entertainment” (B-R and DeFleur, 1976). Gaining a wide variety of important information however does not mean that people are influenced, “Topics are filtered through media information-gathering and –processing systems and then selectively disseminated. The public then sorts out their interest and concern with this information as a function of both their individual differences in personal make-up and their location in societal strata and categories” (B-R and DeFleur, 1976). 
Despite what has been characterized in the literature by many American behavioralists, interpersonal effects influence a person’s decision-making and attitude more than the information they receive from the media. “American voters do not operate in the social vacuum that much of the contemporary voting literature seems to assume. Rather, voters’ enduring personal characteristics interact with messages they are receiving from the social context in which they operate […] interpersonal discussion outweighs the media in affecting the vote” (Beck et. al, 2002). Additionally, recent literature has focused more on the effect that position in one’s social network has a greater effect on voting behavior than does media influence.
“The dependencies people have on media information are a product of the nature of the socio-cultural system, category membership, individual needs, and then number and centrality of the unique information functions that the media system serves for individual and society […] when people’s social realities are entirely adequate before and during message reception, media messages may have little to no alteration effects” (B-R, DeFleur, 1976). 
Operating under a constructivist model and dependency theory one can begin to understand how media is just one factor of a greater social system that can shape one’s attitude and behavior. The 2012 and 2016 elections are two great case studies for this project because of the prominence of both traditional forms of media and social media. Given the attention paid to the 2016 election in regards to “fake news”, media bombshells and negative ads, we should expect media attention to have increased from the 2012 election. Within the scope of this paper, I believe that while media attentiveness has increased from 2012 to 2016, I do not believe this impacts one type of voter or one party more than the other. Further I believe that the accessibility of media to younger voters will result in more media attention paid by younger voters and expect media attention to taper off with older voters. 



# Data and Methods

# Results

# Conclusions

# References

Armoudian, M., Crigler, A. N., & Leighley, J. E. (2010). Constructing the vote: Media effects in a constructionist model. In The Oxford handbook of American elections and political behavior. Oxford University Press.

Ball-Rokeach, S. J., & DeFleur, M. L. (1976). A dependency model of mass-media effects. Communication research, 3(1), 3-21.

Baum, M. A., & Jamison, A. S. (2006). The Oprah effect: How soft news helps inattentive citizens vote consistently. The Journal of Politics, 68(4), 946-959.

DellaVigna, S., & Kaplan, E. (2007). The Fox News effect: Media bias and voting. The Quarterly Journal of Economics, 122(3), 1187-1234.

Gamson, W. A. (1988). The 1987 distinguished lecture: A constructionist approach to mass media and public opinion. Symbolic interaction, 11(2), 161-174.

Garthwaite, C., & Moore, T. J. (2012). Can celebrity endorsements affect political outcomes? Evidence from the 2008 US democratic presidential primary. The journal of law, economics, & organization, 29(2), 355-384.

Gurevitch, M., Bennett, T., Curran, J., & Woollacott, J. (Eds.). (1982). Culture, society and the media (Vol. 759). London: Methuen.

Klapper, J. T. (1960). The effects of mass communication.


Neuman, W. R., & Guggenheim, L. (2011). The evolution of media effects theory: A six-stage model of cumulative research. Communication Theory, 21(2), 169-196.


Zaller, J. R. (1992). The nature and origins of mass opinion. Cambridge university press

